# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://alpental.us
title: Alpental.us
email: hello@alpental.us
author: Alpental.us
description: Congratulations, you made it.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/
  - title: github
    url: https://github.com/
  - title: linkedin
    url: https://linkedin.com/
